---
# Connect to a remote host as root and perform initial access configuration:
#
# * create automation user 'ansible' with passwordless sudo and add SSH key
# * set root password
# * remove /root/.ssh/authorized_keys to prevent direct root login
# * SSH server hardening (disable password auth etc)
# * change SSH port to 54018
#
# Usage:
# ansible-playbook -i "<remote host IP>," init-remote.yml

- name: Initial configuration of SSH service, root access, and 'ansible' user (with passwordless sudo). Changes SSH port to {{ new_sshd_port }}.
  hosts: all
  remote_user: root
  port: 22
  become: true

  vars:

    # New sshd port
    new_sshd_port: 54018

    # Automation user settings
    automation_user: "ansible"

    # Public key content.
    # To create a new key pair (-N for a passwordless key) on a Linux system run:
    # ssh-keygen -t ed25519 -C "ansible-automation" -f ./id_ed25519_ansible -N ""
    # For legacy systems without Ed25519 support:
    # ssh-keygen -t rsa -b 4096 -C "legacy-rsa-key" -f ./id_rsa_ansible -N ""
    ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMYrOqNbFriGsrkPSGi92gFexj7X96iV5nBlOjPdVQIq ansible-automation"

    # Hashed password (SHA 512); to generate it on a Linux system run:
    # mkpasswd --method=sha-512
    root_password_sha512_hash: "$6$SYn0KeQ4sZsWfhYV$zF/mXHCdi82eC..8.9UZnNPPtSaul3JTKfEq4aGmNH/jDpWD5pTqFC.IeYFHPr6Twvs6CKp4qGlGuxCPuoYRB."

  tasks:

    - name: Ensure /usr/bin/sudo has SUID permission
      ansible.builtin.file:
        path: /usr/bin/sudo
        mode: 'u+s'

    # --- Automation User ---

    - name: Create automation user '{{ automation_user }}'
      ansible.builtin.user:
        name: "{{ automation_user }}"
        shell: /bin/bash
        create_home: true
        state: present

    - name: Add SSH key to automation user's authorized_keys
      ansible.posix.authorized_key:
        user: "{{ automation_user }}"
        state: present
        key: "{{ ssh_public_key }}"
        manage_dir: true

    - name: Configure passwordless sudo for user '{{ automation_user }}'
      ansible.builtin.copy:
        content: "{{ automation_user }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ automation_user }}"
        owner: root
        group: root
        mode: '0440'
        validate: /usr/sbin/visudo -cf %s

    # --- Root Configuration ---

    - name: Remove root's authorized_keys
      ansible.builtin.file:
        path: /root/.ssh/authorized_keys
        state: absent

    - name: Change root password
      ansible.builtin.user:
        name: root
        password: "{{ root_password_sha512_hash }}"

    # --- Detect SSH Service Name ---

    - name: "Get services info"
      ansible.builtin.service_facts:

    - name: "Detect SSH service name for current OS (ssh or sshd)"
      ansible.builtin.set_fact:
        ssh_service_name: "{{ 'ssh' if 'ssh.service' in ansible_facts.services else 'sshd' }}"

    - name: Detected SSH service name
      ansible.builtin.debug:
        msg: "{{ ssh_service_name }}"

    # --- SSH Server Hardening ---

    - name: Configure SSH service
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: /usr/sbin/sshd -t -f %s
      loop:
        - { regexp: '^\s*#*PermitRootLogin\s+', line: 'PermitRootLogin prohibit-password' }
        - { regexp: '^\s*#*PasswordAuthentication\s+', line: 'PasswordAuthentication no' }
        - { regexp: '^\s*#*PermitEmptyPasswords\s+', line: 'PermitEmptyPasswords no' }
        - { regexp: '^\s*#*ChallengeResponseAuthentication\s+', line: 'ChallengeResponseAuthentication no' }
      notify: Restart SSH service

    - name: Change SSH port to {{ new_sshd_port }}
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^\s*#*Port\s+'
        line: 'Port {{ new_sshd_port }}'
        state: present
        validate: /usr/sbin/sshd -t -f %s
      notify: Restart SSH service

  handlers:
    - name: Restart SSH service
      ansible.builtin.service:
        name: "{{ ssh_service_name }}"
        state: restarted
