---
- name: Rebuild aliases
  ansible.builtin.command: /usr/bin/newaliases
  changed_when: true
  failed_when: false

- name: Update exim4 config
  ansible.builtin.command: update-exim4.conf
  notify: "exim4 : Restart exim4"
  changed_when: true

- name: Restart exim4
  ansible.builtin.service:
    name: exim4
    state: restarted
