---
- name: Install exim4
  ansible.builtin.apt:
    name: exim4
    state: present
  notify: "exim4 : Rebuild aliases"

- name: Configure /etc/mailname
  ansible.builtin.copy:
    src: mailname
    dest: /etc/mailname
    owner: root
    group: root
    mode: '0644'
  notify: "exim4 : Update exim4 config"

- name: Configure /etc/exim4/update-exim4.conf.conf
  ansible.builtin.copy:
    src: update-exim4.conf.conf
    dest: /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode: '0644'
  notify: "exim4 : Update exim4 config"

- name: Add smtp.gmail.com example to /etc/exim4/passwd.client
  ansible.builtin.lineinfile:
    path: /etc/exim4/passwd.client
    line: '#smtp.gmail.com:user@gmail.com:aaaa bbbb cccc dddd'

- name: Ensure exim4 is enabled and running
  ansible.builtin.service:
    name: exim4
    enabled: true
    state: started

- name: Apply configuration changes (if there are any) by flushing handlers
  ansible.builtin.meta: flush_handlers
