Port 54018

# Logging
SyslogFacility AUTH
LogLevel INFO

# Authentication
PubkeyAuthentication yes
PasswordAuthentication no
PermitRootLogin no
PermitEmptyPasswords no
HostbasedAuthentication no
ChallengeResponseAuthentication no
LoginGraceTime 15
MaxAuthTries 10
StrictModes yes

# Allow legacy client connections (old Linux systems).
KexAlgorithms +diffie-hellman-group1-sha1
Ciphers +aes128-cbc

# Don't read the user's ~/.rhosts and ~/.shosts files
IgnoreRhosts yes

GSSAPIAuthentication no

X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes

MaxStartups 10:30:20

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

Subsystem sftp internal-sftp -l VERBOSE -f LOCAL7

UseDNS no

ClientAliveInterval 15
ClientAliveCountMax 2

AllowGroups ansible z users sftpusers

Match Group sftpusers
    ChrootDirectory /storage/%u
    ForceCommand internal-sftp -l VERBOSE -f LOCAL7
    PasswordAuthentication yes
    MaxSessions 10
    X11Forwarding no
    AllowTcpForwarding no
